dist: trusty
sudo: required

services:
  - docker

install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
  - unzip /tmp/terraform.zip -d /tmp
  - mv /tmp/terraform ~/bin
  - export PATH="~/bin:$PATH"

before_script:
  - terraform init ./deploy

jobs:
  include:
    - stage: build_push
      script: bash ./build_and_push_ecr.sh
    - stage: plan
      script: terraform plan ./deploy
    - stage: deploy
      script: terraform apply ./deploy

stages:
  - build_push
  - plan
  - name: deploy
