dist: trusty
sudo: required

jobs:
  include:
    - stage: test
      install:
        - docker-compose build
        - docker-compose run web yarn db:init
      after_success:
        - codecov
      script:
        - docker-compose run web yarn lint
        - docker-compose run web yarn test
    - stage: deploy
      install: skip
      script:
        - bash ./deploy-container.sh

stages:
  - test
  - name: deploy
    if: branch = master
