sudo: required

language: node_js
node_js:
  - '9.2'

addons:
  chrome: stable

services:
  - mysql

addons:
  ssh_known_hosts:
  - maija.tko-aly.fi
  - uolevi.tko-aly.fi

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=3010 http://localhost
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `tkoaly-user-service_test`;'
  - npm install -g yarn
  - npm install -g codecov

install:
  - yarn install --dev
  - yarn migrate
  - yarn seed

script:
  - yarn lint
  - yarn test
  - yarn browser-test

after_success:
  - codecov
