sudo: required

language: node_js
node_js:
  - '8'

services:
  - mysql

addons:
  ssh_known_hosts:
  - maija.tko-aly.fi
  - uolevi.tko-aly.fi

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `tkoaly-user-service_test`;'
  - npm install -g yarn

install:
  - yarn install
  - yarn global add knex
  - knex migrate:latest
  - knex seed:run

script:
  - yarn test
  
deploy:
  provider: script
  script: scripts/deploy.sh staging
  on:
    branch: dev