sudo: required

language: node_js
node_js:
  - '8'

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `tkoaly-user-service_test`;'

install:
  - yarn install
  - yarn global add knex
  - knex migrate:latest
  - knex seed:run

script:
  - yarn test
  
