dist: trusty
sudo: required

branches:
  only:
    - master

services:
  - docker

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

install:
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
  - unzip /tmp/terraform.zip -d /tmp
  - mv /tmp/terraform ~/bin
  - export PATH="~/bin:$PATH"

before_script:
  - terraform init "./deploy"

jobs:
  include:
    - stage: build_push
      script: bash ./build_and_push_ecr.sh
    - stage: plan
      script: bash ./deploy/scripts/terraform_plan.sh $TRAVIS_BUILD_NUMBER
    - stage: deploy
      script: bash ./deploy/scripts/terraform_apply.sh $TRAVIS_BUILD_NUMBER
      after_success: bash ./deploy/scripts/cleanup.sh $TRAVIS_BUILD_NUMBER

stages:
  - build_push
  - plan
  - name: deploy
