sudo: required

language: node_js
node_js:
  - '9.2'

services:
  - mysql

addons:
  ssh_known_hosts:
  - maija.tko-aly.fi
  - uolevi.tko-aly.fi

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `tkoaly-user-service_test`;'
  - npm install -g typescript
  - npm install -g ts-node
  - npm install -g yarn
  - npm install -g codecov

install:
  - yarn install
  - yarn global add knex
  - knex migrate:latest
  - knex seed:run

script:
  - yarn lint
  - yarn test

after_success:
  - codecov
