dist: trusty
sudo: required

services:
  - docker

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - mkdir -p ~/$TRAVIS_BUILD_NUMBER
  - aws s3 sync s3://user-service-state/plan-$TRAVIS_BUILD_NUMBER ~/$TRAVIS_BUILD_NUMBER

install:
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
  - unzip /tmp/terraform.zip -d /tmp
  - mv /tmp/terraform ~/bin
  - export PATH="~/bin:$PATH"

before_script:
  - terraform init ./deploy

jobs:
  include:
    - stage: build_push
      script: bash ./build_and_push_ecr.sh
    - stage: plan
      script: cd ./deploy
      script: terraform plan --out=~/$TRAVIS_BUILD_NUMBER
      script: aws s3 sync s3://user-service-state/plan-$TRAVIS_BUILD_NUMBER ~/$TRAVIS_BUILD_NUMBER
    - stage: deploy
      script: cd ./deploy
      script: terraform apply ~/$TRAVIS_BUILD_NUMBER
      after_success: aws s3 rm --recursive s3://user-service-state/plan-$TRAVIS_BUILD_NUMBER

stages:
  - build_push
  - plan
  - name: deploy
