version: '3.7'
volumes:
  mysql-data:
services:
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: unsecure
      MYSQL_DATABASE: user-service_dev
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    build:
      context: .
      shm_size: 1G
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    environment:
      USERSERVICE_PORT: 8080
      NODE_ENV: development
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: unsecure
      DB_NAME: user-service
      SESSION_SECRET: unsecure
